### ISSUE TITLE
solo got problem

### ISSUE THREAD

**Issue by bangdrie** [Afiniel-tech/yiimpool_yiimp_single#4]
There is a miner in my pool with 10 workers. 4 of them are mining solo. If ANY of his rigs find a block, he gets paid the whole block reward just like all his workers are in solo. Also, if any other miner hits a block, he gets a share according to his hashrates!

**Comment by afiniel** [comment]
<h1 align="center"> Hey! Sorry for late </h2>
I have been on other things. Anyway it should be fixed now on on this Afiniel-tech/yiimp/pull/5
Remember if you still find a problem with it feel free to open issue again
